export const LINKS = {
    // Main Navigation
    HOME: '/',
    ABOUT: '/about-us',
    CONTACT: '/contact',
    LOGIN: '/login',
    REGISTER: '/register',
    PROFILE: '/profile',
    LOGOUT: '/logout',
    NOT_FOUND: '/404',
    SERVER_ERROR: '/500',
    LIST_YOUR_PROPERTY:'/list-property',
    SPAS: '/spas',
    EVENT_VENUES: '/events',
    EVENT_VENUES_SEARCH: '/events/search',
    VENUE_TYPE: '/events/venue-types',
    RESTAURANTS: '/restaurants',
    HOURLY_ROOMS: '/hourly-rooms',

    // Company Links
    TERMS_CONDITIONS: '/terms-conditions',
    PRIVACY_POLICY: '/privacy-policy',
    USER_AGREEMENT: '/how-spodia-helps',
    CUSTOMER_SUPPORT: '/customer-support',
    CAREER: '/career',
    CSR: '/csr',
    SPODIA_MOBILE: '/spodia-mobile',
    FAQS: '/faqs',
    INVESTOR_RELATIONS: '/investor-relations',
    COMPANY_DETAILS: '/company-details',
    BOOKING_POLICY: '/booking-policy',
    SEARCH_RESULTS:'/search-results',

    // Hotel Links - Domestic
    HOTELS_DELHI: '/in/hotels/delhi/hotels',
    HOTELS_GOA: '/in/hotels/goa/hotels',
    HOTELS_GUWAHATI: '/in/hotels/guwahati/hotels',
    HOTELS_PUNE: '/in/hotels/pune/hotels',
    HOTELS_AGRA: '/in/hotels/agra/hotels',
    HOTELS_JAIPUR: '/in/hotels/jaipur/hotels',
    HOTELS_MUMBAI: '/in/hotels/mumbai/hotels',
    HOTELS_HYDERABAD: '/in/hotels/hyderabad/hotels',
    HOTELS_MYSORE: '/in/hotels/mysore/hotels',
    HOTELS_CHENNAI: '/in/hotels/chennai/hotels',
    HOTELS_MANALI: '/in/hotels/manali/hotels',
    HOTELS_BANGALORE: '/in/hotels/bangalore/hotels',
    HOTELS_AHMEDABAD: '/in/hotels/ahmedabad/hotels',
    HOTELS_MUNNAR: '/in/hotels/munnar/hotels',
    HOTELS_KOLKATA: '/in/hotels/kolkata/hotels',
    HOTELS_OOTY: '/in/hotels/ooty/hotels',
    HOTELS_MAHABALESHWAR: '/in/hotels/mahabaleshwar/hotels',
    HOTELS_SHIMLA: '/in/hotels/shimla/hotels',
    HOTELS_NAINITAL: '/in/hotels/nainital/hotels',

    // Hotel Links - International
    HOTELS_DUBAI: '/dubai/hotels',
    HOTELS_SINGAPORE: '/singapore/hotels',
    HOTELS_BANGKOK: '/bangkok/hotels',
    HOTELS_PARIS: '/paris/hotels',
    HOTELS_KRABI: '/krabi/hotels',
    HOTELS_BALI: '/bali/hotels',
    HOTELS_HONG_KONG: '/hong-kong/hotels',
    HOTELS_ABU_DHABI: '/abu-dhabi/hotels',
    HOTELS_MOSCOW: '/moscow/hotels',
    HOTELS_DHAKA: '/dhaka/hotels',
    HOTELS_KATHMANDU: '/kathmandu/hotels',
    HOTELS_LONDON: '/london/hotels',
    HOTELS_AMSTERDAM: '/amsterdam/hotels',
    HOTELS_COLOMBO: '/colombo/hotels',
    HOTELS_MALDIVES: '/maldives/hotels',
    HOTELS_ROME: '/rome/hotels',
    HOTELS_KUALA_LUMPUR: '/kuala-lumpur/hotels',
    HOTELS_PATTAYA: '/pattaya/hotels',
    HOTELS_ZURICH: '/zurich/hotels',

    // Hotels by Area
    HOTELS_PANCHGANI: '/in/hotels/panchgani/hotels/',
    HOTELS_JUHU: '/in/hotels/juhu/hotels/',
    HOTELS_SRISAILAM: '/in/hotels/srisailam/hotels/',
    HOTELS_BANDRA: '/in/hotels/bandra/hotels/',
    HOTELS_GOA_BEACH: '/in/hotels/goa-beach/hotels/',
    HOTELS_AULI: '/in/hotels/auli/hotels/',
    HOTELS_ERNAKULAM: '/in/hotels/ernakulam/hotels/',
    HOTELS_FORT_KOCHI: '/in/hotels/fort-kochi/hotels/',
    HOTELS_TAKI: '/in/hotels/taki/hotels/',
    HOTELS_PALOLEM: '/in/hotels/palolem/hotels/',
    HOTELS_POWAI: '/in/hotels/powai/hotels/',
    HOTELS_COLABA: '/in/hotels/colaba/hotels/',
    HOTELS_BANDRA_WEST: '/in/hotels/bandra-west/hotels/',
    HOTELS_PURI_BEACH: '/in/hotels/puri-beach/hotels/',
    HOTELS_PANJIM: '/in/hotels/panjim/hotels/',
    HOTELS_MALAD_WEST: '/in/hotels/malad-west/hotels/',
    HOTELS_THIRUKADAIYUR: '/in/hotels/thirukadaiyur/hotels/',
    HOTELS_BAGA: '/in/hotels/baga/hotels/',
    HOTELS_CONNAUGHT_PLACE: '/in/hotels/connaught-place/hotels/',
    HOTELS_CALANGUTE: '/in/hotels/calangute/hotels/',
    HOTELS_GOA_AIRPORT: '/in/hotels/goa-airport/hotels/',

    // Homestays
    HOMESTAYS_COORG: '/in/coorg/homestays',
    HOMESTAYS_OOTY: '/in/ooty/homestays',
    HOMESTAYS_SAKLESHPUR: '/in/sakleshpur/homestays',
    HOMESTAYS_DARJEELING: '/in/darjeeling/homestays',
    HOMESTAYS_WAYANAD: '/in/wayanad/homestays',
    HOMESTAYS_MUNNAR: '/in/munnar/homestays',
    HOMESTAYS_KODAIKANAL: '/in/kodaikanal/homestays',

    // Villas
    VILLAS_LONAVALA: '/in/lonavala/villas',
    VILLAS_GOA: '/in/goa/villas',
    VILLAS_IGATPURI: '/in/igatpuri/villas',
    VILLAS_KARJAT: '/in/karjat/villas',
    VILLAS_ALIBAUG: '/in/alibaug/villas',
    VILLAS_MAHABALESHWAR: '/in/mahabaleshwar/villas',
    VILLAS_PONDICHERRY: '/in/pondicherry/villas',

    // Resorts
    RESORTS_JIM_CORBETT: '/in/jim-corbett/resorts',
    RESORTS_GOKARNA: '/in/gokarna/resorts',
    RESORTS_MANESAR: '/in/manesar/resorts',
    RESORTS_ABU_MANESAR: '/in/abu-manesar/resorts',
    RESORTS_BANDIPUR: '/in/bandipur/resorts',
    RESORTS_KANAKAPURA: '/in/kanakapura/resorts',

    // 5 Star Hotels
    FIVE_STAR_DHARAMSHALA: '/in/hotels/dharamshala/5-star',
    FIVE_STAR_NAINITAL: '/in/hotels/nainital/5-star',
    FIVE_STAR_SURAT: '/in/hotels/surat/5-star',
    FIVE_STAR_DALHOUSIE: '/in/hotels/dalhousie/5-star',
    FIVE_STAR_RANCHI: '/in/hotels/ranchi/5-star',
    FIVE_STAR_MOUNT_ABU: '/in/hotels/mount-abu/5-star',
    FIVE_STAR_BANGALORE: '/in/hotels/bangalore/5-star',
    FIVE_STAR_COORG: '/in/hotels/coorg/5-star',
    FIVE_STAR_GANGTOK: '/in/hotels/gangtok/5-star',
    FIVE_STAR_MADURAI: '/in/hotels/madurai/5-star',
    FIVE_STAR_RAIPUR: '/in/hotels/raipur/5-star',
    FIVE_STAR_SHILLONG: '/in/hotels/shillong/5-star',
    FIVE_STAR_MATHERAN: '/in/hotels/matheran/5-star',
    FIVE_STAR_PORT_BLAIR: '/in/hotels/port-blair/5-star',
    FIVE_STAR_RANTHAMBORE: '/in/hotels/ranthambore/5-star',
    FIVE_STAR_ANDAMAN: '/in/hotels/andaman/5-star',

    // Budget Hotels
    BUDGET_HOTELS_GOA: '/in/budget-hotels/goa',
    BUDGET_HOTELS_JAIPUR: '/in/budget-hotels/jaipur',
    BUDGET_HOTELS_OOTY: '/in/budget-hotels/ooty',
    BUDGET_HOTELS_KERALA: '/in/budget-hotels/kerala',
    BUDGET_HOTELS_MUMBAI: '/in/budget-hotels/mumbai',
    BUDGET_HOTELS_NAINITAL: '/in/budget-hotels/nainital',
    BUDGET_HOTELS_CHENNAI: '/in/budget-hotels/chennai',
    BUDGET_HOTELS_CHANDIGARH: '/in/budget-hotels/chandigarh',
    BUDGET_HOTELS_PUNE: '/in/budget-hotels/pune',
    BUDGET_HOTELS_AGRA: '/in/budget-hotels/agra',
    BUDGET_HOTELS_AHMEDABAD: '/in/budget-hotels/ahmedabad',
    BUDGET_HOTELS_GANGTOK: '/in/budget-hotels/gangtok',

    // Generic Links
    DOMESTIC_HOTELS: '#',
    HOTELS_INDIA: '#',
    HOTELS_NEAR_ME: '#',
    SITEMAP: '/sitemap.xml',
}


export const CONTACT_INFO ={
title:"Hotel Specialist",
eventTitle:"Event Specialist",
mobile1:"+918800842084",
mobile2:"+917399666688",
email1:"hotels@spodia.in",
email2:"support@spodia.in",
email3:"care@spodia.in",
contactEmail:"contact@spodia.in",
helloEmail:"hello@spodia.in",
address:"Spodia, 2nd Floor, 4, 4th Cross, 1st Main Road, 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038",

}